service:
  name: ecommly-api

plugins:
  - serverless-webpack
  - serverless-stage-manager
  - serverless-iam-roles-per-function
  # - serverless-aws-documentation
  # - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    REGION: ${self:provider.region}
    IMAGES_BUCKET_NAME: ecommly-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    PRODUCTS_TABLE: Products-${self:provider.stage}
    ORDERS_TABLE: Orders-${self:provider.stage}
    TEST_SECRET: ${self:custom.TEST_SECRET}
    USER_POOL_ID: ${self:custom.USER_POOL_ID}
    USER_POOL_CLIENT_ID: ${self:custom.USER_POOL_CLIENT_ID}
    ADMIN_GROUP: Admin-${self:provider.stage}
    CUSTOMER_GROUP: Customer-${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true

custom:
  stages:
    - develop
    - production
  TEST_SECRET: ${ssm:test-${self:provider.stage}-secret}
  USER_POOL_ID: ${ssm:userpool-${self:provider.stage}-id}
  USER_POOL_CLIENT_ID: ${ssm:client-${self:provider.stage}-id}

functions:
  hello:
    handler: src/lambda/hello.handler
    events:
      - http:
          method: get
          path: hello
  signup:
    handler: src/lambda/auth/signup.handler
    events:
      - http:
          method: post
          path: signup
  signin:
    handler: src/lambda/auth/signin.handler
    events:
      - http:
          method: post
          path: signin
  postConfirmed:
    handler: src/lambda/auth/postConfirmed.handler
    events:
      - http:
          method: post
          path: confirmed
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminAddUserToGroup
        Resource: "*"
  products:
    handler: src/lambda/products/getProducts.handler
    events:
      - http:
          method: get
          path: products
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  createProduct:
    handler: src/lambda/products/createProduct.handler
    events:
      - http:
          method: post
          path: products
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  uploadImage:
    handler: src/lambda/images/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: upload
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources: ${file(./src/resources/resources.yml)}
