service:
  name: ecommly-api

plugins:
  - serverless-webpack
  - serverless-stage-manager
  # - serverless-aws-documentation
  # - serverless-reqvalidator-plugin
  # - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    IMAGES_BUCKET_NAME: ecommly-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    PRODUCTS_TABLE: Products-${self:provider.stage}
    ORDERS_TABLE: Orders-${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true

custom:
  stages:
    - develop
    - production

functions:
  hello:
    handler: src/lambda/hello.handler
    events:
      - http:
          method: get
          path: hello
  products:
    handler: src/lambda/products/getProducts.handler
    events:
      - http:
          method: get
          path: products
          cors: true
          authorizer:
            type: cognitoUserPool
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources: ${file(./src/resources/resources.yml)}
